/**
 * Author: zhangxin
 * Time: 2016/11/5 0005.
 * Desc:
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {

        int[] tmp = new int[26];
        for (int i = 0; i < s.length(); i++) {
            tmp[s.charAt(i) - 97]--;
        }

        for (int i = 0; i < t.length(); i++) {
            tmp[t.charAt(i) - 97]++;
        }

        for (int i = 0; i < tmp.length; i++) {
            if (tmp[i] == 1) {
                return (char) (i + 97);
            }
        }
        return ' ';
    }

    public char findTheDifference2(String s, String t) {
        //先拿到 t 的第一个 字符, t 比 s 多一个字符;
        int res = (int) t.charAt(0);

        for (int i = 0; i < s.length(); ++i) {
            res = res ^ (int) s.charAt(i);
            res = res ^ (int) t.charAt(i + 1);
        }
        return (char) res;
    }

    public static void main(String[] args) {
        int i = 2;
        System.out.println((char) (i + 97));
    }
}
